manajemen_gudang/manajemen_gudang/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from produk import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("produk.urls")),
    path('fetch-api/', views.fetch_and_save_data),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manajemen_gudang/produk/urls.py
from django.urls import path

from . import views

app_name = "produk"

urlpatterns = [
    path("", views.ProdukListView.as_view(), name="list"),
    path("create/", views.ProdukCreateView.as_view(), name="create"),
    path("update/<int:pk>", views.ProdukUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", views.ProdukDeleteView.as_view(), name="delete"),
]

manajemen_gudang/produk/models.py
from django.db import models


class Produk(models.Model):
    nama_produk = models.CharField(max_length=255, blank=False)
    harga = models.IntegerField(blank=False)
    kategori = models.ForeignKey("Kategori", on_delete=models.CASCADE)
    status = models.ForeignKey("Status", on_delete=models.CASCADE)

    def __str__(self):
        return self.nama_produk


class Kategori(models.Model):
    nama_kategori = models.CharField(max_length=100)

    def __str__(self):
        return self.nama_kategori


class Status(models.Model):
    nama_status = models.CharField(max_length=20)

    def __str__(self):
        return self.nama_status

manajemen_gudang/produk/views.py
import requests
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import View
from .models import Produk, Kategori, Status
from .serializers import ProdukSerializer

from rest_framework import generics, status
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response


def fetch_and_save_data(request):
    url = "https://recruitment.fastprint.co.id/tes/api_tes_programmer"
    payload = {
        "username": "tesprogrammer110125C21",
        "password": "4ac0087b411a38bad7c428dd1add9a8b"
    }

    response = requests.post(url, data=payload)

    if response.status_code == 200:
        api_data = response.json()

        # Menyimpan data ke database
        for item in api_data['data']:
            kategori_object, _ = Kategori.objects.get_or_create(nama_kategori=item['kategori'])
            status_object, _ = Status.objects.get_or_create(nama_status=item['status'])
            produk_data = {
                "nama_produk": item['nama_produk'],
                "harga": int(item['harga']),
                "kategori": kategori_object,
                "status": status_object
            }
            serializer = ProdukSerializer(data=produk_data)
            if serializer.is_valid():
                serializer.save()
            else:
                print(serializer.errors)

        return JsonResponse({"message": "Data berhasil disimpan ke database."})

    else:
        return JsonResponse({
            "error": f"Gagal memanggil API: {response.status_code}",
            "details": response.text
        }, status=response.status_code)


class ProdukListView(generics.ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "produk/list.html"

    def get_queryset(self):
        status_bisa_dijual = Status.objects.get(nama_status="bisa dijual")
        return Produk.objects.filter(status=status_bisa_dijual)

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        return Response({'produks': queryset})


class ProdukCreateView(generics.CreateAPIView):
    queryset = Produk.objects.all()
    serializer_class = ProdukSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "produk/create.html"

    def get(self, request, *args, **kwargs):
        serializer = self.serializer_class()
        return Response({'serializer': serializer})

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            messages.success(request, "Produk berhasil ditambahkan.")
            return HttpResponseRedirect(reverse("produk:list"))
        return Response({'serializer': serializer, 'errors': serializer.errors}, status=status.HTTP_400_BAD_REQUEST)


class ProdukUpdateView(generics.UpdateAPIView):
    queryset = Produk.objects.all()
    serializer_class = ProdukSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "produk/update.html"

    def get(self, request, *args, **kwargs):
        produk = get_object_or_404(Produk, pk=kwargs.get('pk'))
        serializer = self.serializer_class(instance=produk)
        return Response({'serializer': serializer})

    def post(self, request, *args, **kwargs):
        produk = get_object_or_404(Produk, pk=kwargs.get('pk'))
        serializer = self.serializer_class(instance=produk, data=request.data)
        if serializer.is_valid():
            serializer.save()
            messages.success(request, "Produk berhasil diedit.")
            return HttpResponseRedirect(reverse("produk:list"))
        return Response({'serializer': serializer, 'errors': serializer.errors}, status=status.HTTP_400_BAD_REQUEST)


class ProdukDeleteView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.method == 'DELETE':
            return self.delete(request, *args, **kwargs)
        return JsonResponse({'error': 'Method not allowed'}, status=405)

    def delete(self, request, *args, **kwargs):
        produk = get_object_or_404(Produk, pk=kwargs.get('pk'))
        produk.delete()
        return JsonResponse({'message': 'Produk berhasil dihapus'}, status=200)

manajemen_gudang/produk/templates/produk/create.html
{% extends "base.html" %}

{% load rest_framework %}

{% block content %}

  <main id="main" class="main">

    <section class="section">

      <div class="card">
            <div class="card-body">
              <h5 class="card-title">Tambah Produk</h5>
              <!-- Vertical Form -->
              <form class="row g-3" method="post">
                {% csrf_token %}
                {% render_form serializer %}
                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
              </form><!-- Vertical Form -->

            </div>
          </div>

    </section>

  </main>

{% endblock %}

manajemen_gudang/produk/templates/produk/list.html
{% extends "base.html" %}

{% block content %}
  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Produk</h1>
    </div><!-- End Page Title -->

      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endif %}

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List Produk</h5>

              <!-- Table with stripped rows -->
              <table class="table datatable">
                <thead>
                  <tr>
                    <th style="width: 40%">
                      Nama Produk
                    </th>
                    <th>Harga</th>
                    <th>Kategori</th>
                    <th>Status</th>
                    <th>Aksi</th>
                  </tr>
                </thead>
                <tbody>
                    {% for produk in produks %}
                        <tr>
                            <td>{{ produk }}</td>
                            <td>Rp. {{ produk.harga }}</td>
                            <td>{{ produk.kategori }}</td>
                            <td>{{ produk.status }}</td>
                            <td>
                                <a href="{% url 'produk:update' produk.id %}">
                                    <i class="fa fa-pencil-square-o text-warning" aria-hidden="true"></i>
                                </a>
                                <a href="{% url 'produk:delete' produk.id %}" class="delete-button">
                                    <i class="fa fa-trash text-danger" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main>

{% endblock content %}

{% block js %}

    <script>
        $(".delete-button").on("click", function(e) {
            e.preventDefault();
            let url = $(this).attr("href");
            $.confirm({
                title: 'Hapus produk ini?',
                content: 'Produk yang dihapus tidak dapat dikembalikan!',
                buttons: {
                    confirm: {
                        text: 'Ya, Hapus!',
                        btnClass: 'btn-danger',
                        action: function () {
                            $.ajax({
                                url: url,
                                type: 'DELETE',
                                headers: {
                                    'X-CSRFToken': '{{ csrf_token }}'
                                },
                                success: function(response) {
                                    $.alert('Produk berhasil dihapus!');
                                    setTimeout(function () {
                                        location.reload();
                                    }, 2000);
                                },
                                error: function(xhr, status, error) {
                                    $.alert('Gagal menghapus produk.');
                                }
                            });
                        }
                    },
                    cancel: {
                        text: 'Batal',
                        btnClass: 'btn-seccondary',
                        action: function () {
                            $.alert('Produk Batal dihapus!');
                        }
                    },
                }
            });
        })
    </script>

{% endblock js %}

manajemen_gudang/produk/templates/produk/update.html
{% extends "base.html" %}

{% load rest_framework %}

{% block content %}

  <main id="main" class="main">

    <section class="section">

      <div class="card">
            <div class="card-body">
              <h5 class="card-title">Edit Produk</h5>
              <!-- Vertical Form -->
              <form class="row g-3" method="post">
                {% csrf_token %}
                {% render_form serializer %}
                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
              </form><!-- Vertical Form -->

            </div>
          </div>

    </section>

  </main>

{% endblock %}

manajemen_gudang/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Produk - Rizqulloh Rayhan Ferdiansyah</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.css">
  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'header.html' %}
  <!-- End Header -->

  <!-- ======= Sidebar ======= -->
  {% include 'sidebar.html' %}
  <!-- End Sidebar-->

  {% block content %}
  {% endblock %}

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>

  {% block js %}
  {% endblock %}

</body>

</html>

manajemen_gudang/templates/header.html
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <span class="d-none d-lg-block">Produk</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

  </header>

manajemen_gudang/templates/navbar.html
<!-- As a link -->
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
  </div>
</nav>

manajemen_gudang/templates/sidebar.html
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'produk:list' %}">
          <i class="bi bi-grid"></i>
          <span>List Produk</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'produk:create' %}">
          <i class="bi bi-grid"></i>
          <span>Tambah Produk</span>
        </a>
      </li>

    </ul>

  </aside>